### DISCUSSION TITLE
How can I correctly use `Lua::init_from_ptr`?

### DISCUSSION THREAD

**Discussion by shanebishop** [mlua-rs/mlua#430] [Q&A] [answered]
I am getting a segfault when trying to use `Lua::init_from_ptr`. I built a minimal reproducible example.

`src/lib.rs`:
```rust
use libc::c_int;
use mlua::lua_State;
use mlua::prelude::*;

#[no_mangle]
pub unsafe extern "C" fn luaopen_libmlua_repro(l: *mut lua_State) -> c_int {
    eprintln!("luaopen_li stderr print");

    let _lua = Lua::init_from_ptr(l);

    1
}
```

`Cargo.toml`:
```toml
[package]
name = "mlua-repro"
version = "0.1.0"
edition = "2021"

[dependencies]
mlua = { version = "0.9.9", features = ["lua52"] }
libc = "0.2"

[lib]
crate-type = ["cdylib"]
```

`target/debug/main.lua`:
```lua
require 'libmlua_repro'
```

Build and run:
```
~/src/tmp/mlua-repro$ cargo build
    Finished `dev` profile [unoptimized + debuginfo] target(s) in 0.00s
~/src/tmp/mlua-repro$ cd target/debug/
~/src/tmp/mlua-repro/target/debug$ lua -v
Lua 5.2.4  Copyright (C) 1994-2015 Lua.org, PUC-Rio
~/src/tmp/mlua-repro/target/debug$ lua main.lua
luaopen_li stderr print
Segmentation fault
```

How can I correctly use `Lua::init_from_ptr`?
