### ISSUE TITLE
(0.10-beta+send) segfault calling LuaFunction from another thread

### ISSUE THREAD

**Issue by alemidev** [mlua-rs/mlua#443]
i'm developing a nvim plugin which is mostly a thin wrapper around a native library. such library works in background and wants to invoke callbacks to do arbitrary work on-demand for new events.

a minimal example of my use case:

```toml
# Cargo.toml
[package]
name = "example-mlua"
version = "0.1.0"
edition = "2021"

[lib]
name = "mluaexample"
crate-type = ["cdylib"]

[dependencies]
mlua = { version = "0.10.0-beta.1", features = ["luajit", "send", "module"] }
```

```rust
// lib.rs
use mlua::prelude::*;

#[mlua::lua_module]
fn libmluaexample(lua: &Lua) -> LuaResult<LuaTable> {
  let exports = lua.create_table()?;

  exports.set("callback", lua.create_function(|_, (cb,):(LuaFunction,)| {
    std::thread::spawn(move || {
      let mut count = 0;
      loop {
        std::thread::sleep(std::time::Duration::from_millis(200));
        if cb.call::<(String,),()>((format!("calling callback: {count} errors"),)).is_err() {
          count += 1;
        }
      }
    });
    Ok(())
  })?)?;

  Ok(exports)
}
```

in addition to this, nvim exposes a lua interface to libuv's async handle, which is safe to invoke across threads and will wake the main loop thread to run the wrapped function

```lua
-- your neovim init.lua

local native = require('libmluaexample')
local async = vim.loop.new_async(function() print("something") end)
native.callback(function() async:send() end)
```

with this setup the callback given to the foreign thread should only interact with the async handle, which should be threadsafe. however after requiring the native module neovim will consistently crash after not many invocations.

----

since this is the new beta built this may be a temporary or already known bug, so feel free to close.

also i'm not sure this is supported use at all, i see with the `send` feature enabled lua values hold a mutexed weak ref, but it's not clear to me how this mutex is handled when mlua is a module

if my usage is unsupported, is it possible to clear the callback environment or run it in another context to call it safely? is it possible to lock the lua state and allow callbacks to execute safely from other threads?

anyhow, thanks for the wonderful library and your time, looking forward to mlua 0.10!
