### ISSUE TITLE
`print` function behaves different when called using variable

### ISSUE THREAD

**Issue by rawhuul** [mlua-rs/mlua#458]
Hi, the `print` function behaves differently when called from a variable compared to when it’s executed directly in a code chunk.

Source code as follows:
```rust
use mlua::{prelude::*, Variadic};

fn main() {
    let lua = Lua::new();

    let globals = lua.globals();

    globals.set("x", 10).unwrap();

    let print: LuaFunction = globals.get("print").unwrap();

    // #1: It will not print value of x, rather print `x` as variable
    print.call::<_, ()>(("Value is:", "x")).unwrap();

    // #2: Same as #1
    print
        .call::<_, ()>(Variadic::from_iter(["Value is:", "x"].iter().cloned()))
        .unwrap();

    // #3: It will print value of x, work as expected
    lua.load(r#"print("Value is:", x)"#).exec().unwrap();
}
```

My `Cargo.toml`:
```toml
[package]
name = "ohstat"
version = "0.1.0"
edition = "2021"

[dependencies]
mlua = { version = "0.9.9", default-features = false, features = ["luajit", "vendored"] }

[profile.release]
codegen-units = 1
lto = true
opt-level = 3
panic = "abort"
strip = true

```

Output:
![image](https://github.com/user-attachments/assets/da30690f-83c6-489d-9fca-2f0966fac843)
---
![image](https://github.com/user-attachments/assets/4676acd9-84c5-4a07-8b74-9cc8e5a94c10)
