### ISSUE TITLE
symbol not found: luaopen_...

### ISSUE THREAD

**Issue by kkharji** [mlua-rs/mlua#88]
Hello there, I'm trying to integrate rust into a lua project and I have the following code in lib.rs

```rs
use mlua::prelude::*;
use mlua::SerializeOptions;
use mlua::Value;
use serde::Serialize;

pub fn to_lua<'lua, T>(l: &'lua Lua, t: &T) -> LuaResult<Value<'lua>>
where
    T: Serialize + ?Sized,
{
    l.to_value_with(&t, SerializeOptions::new().serialize_none_to_null(false))
}

fn hello<'lua>(lua: &'lua mlua::Lua, name: String) -> LuaResult<Value<'lua>> {
    let val = format!("hello, {}!", name);
    println!("{}", val);
    to_lua(lua, &val)
    // Ok()
}

#[mlua::lua_module]
fn my_module(lua: &Lua) -> LuaResult<LuaTable> {
    let exports = lua.create_table()?;
    exports.set("hello", lua.create_function(hello)?)?;
    Ok(exports)
}
```
Cargo.toml
```toml
[package]
name = "worktree"
version = "0.1.0"
edition = "2018"

[lib]
crate-type = ["cdylib"]

[dependencies]
# High level bindings to Lua 5.4/5.3/5.2/5.1 (including LuaJIT) with async/await features …
mlua = { version = "0.6.6", features = ["luajit", "vendored", "module", "serialize", "async"] }

```
in .cargo/config I have

```toml
[target.x86_64-apple-darwin]
rustflags = ["-C", "link-args=-rdynamic"]

[target.x86_64-unknown-linux-gnu]
rustflags = ["-C", "link-args=-rdynamic"]
```

and build I ran

`cargo build --release`

Then I moved and renamed `libworktree.dylib` manually to `libworktree.so` and tried to require it in my run time.

`require 'libworktree'`
`dlsym(0x120e065e0,
luaopen_libworktree): symbol not found`

Any idea what might be the cause of this.

Thanks
